"""create_students_table

Revision ID: b8eeb5e4d774
Revises: 
Create Date: 2026-02-21 19:00:39.329417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8eeb5e4d774'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('iep_file_name', sa.String(), nullable=True),
    sa.Column('diagnoses', sa.Text(), nullable=False),
    sa.Column('accommodations', sa.JSON(), nullable=False),
    sa.Column('learning_goals', sa.Text(), nullable=False),
    sa.Column('additional_context', sa.Text(), nullable=False),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('case_manager', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
